services:
  drpyS:
    image: eulac/my-drpys:latest  
    container_name: drpyS
    ports:
      - "9097:5757"
    volumes:
      - ./drpy-node:/drpy-node
    restart: always
    env_file:
      - ./drpy-node/.env.development